### ISSUE TITLE
Select local wifi IP forces one option.

### ISSUE THREAD

**Issue by DonSaltTrue** [ParticulaCode/FoundryVTT-GoDice#17]
I've tried to use the GoDice app to connect to the Foundry TTV on three separate devices, (Ipad, Iphone, Android). With each device the dropdown doesn't display other options for the Ip address.
![image_2023-09-27_172213812](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/135408196/f926b9e9-be08-49e9-a048-98cef67ced69)
Any help would be appreciated.

**Comment by ParticulaCode** [comment]
What is the IP of the computer that running the Foundry server?

**Comment by DonSaltTrue** [comment]
10.0.0.125

**Comment by ParticulaCode** [comment]
Then it should work fine...

Seems like you missed some steps.

1. In order to use you should download the godice-connector.bat file and 'run as administrator' - entering your IP address. This will accept our app's socket certificate.
2. Then, in Foundry, you should use the certificated DNS --> instead of the plain IP address, you should type in the GoDice module config this address: wss://godice-connector.com:8596

Please see the instructions here (also find it through the module config support button):
https://drive.google.com/file/d/15Ksa4JAfPP_M0fW2-32sEUHTvPg5ybz1/view?usp=sharing

here is the RAR with the bat file:
https://drive.google.com/file/d/1rSbjqKtvn0a-fZ2Px2WgpOwBy4z57m_k/view?usp=sharing

**Comment by DonSaltTrue** [comment]
That’s for setting up a ssl connection. I can’t even get past the Wi-Fi ip select screen to start the ssl connection. I gives a oopsy dicey error. Currently the app seems like the problem here.

**Comment by swaters83** [comment]
I'm having the same issue with Andriod.  I've rebooted devices, reinstalled, turned off cell data and even tried the ssl step above.  None of it works.

**Comment by ParticulaCode** [comment]
Hey, can you please check if the latest GoDice Application version fixed your issue?

**Comment by swaters83** [comment]
It did.

Thank you,

Steve W

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
