### ISSUE TITLE
Websocket over HTTPs

### ISSUE THREAD

**Issue by ncsululu** [ParticulaCode/FoundryVTT-GoDice#2]
The module will not allow the websocket connection to the godice app when the Foundry system is using HTTPS. The following error is received:
_An insecure WebSocket connection may not be initiated from a page loaded over HTTPS_

**Comment by myzar472** [comment]
I realized this in Issue 3. I don't think the GoDice app runs WSS:// and only can run WS://

Until the GoDice App is able to run WSS, we won't be able to load on Foundry running HTTPS/SSL.

**Comment by Anchor8900** [comment]
I was also having problems with HTTPS and WS, Finally found a setting in EDGE to Allow Insecure Content and that cleared up part of my problem. Now to figure out why my PF2r Attacks don't request dice rolls.

**Comment by AKparticula** [comment]
@myzar472 @ncsululu 
The module and the app were updated to enable two different solutions for ssl.

**Comment by AKparticula** [comment]
Hi @Simon-Stone , Thanks for sharing.
Seems like you missed some steps. 
1. In order to use the was function you should download the godice-connector.bat file and 'run as administrator' - entering your IP address. This will accept our app's socket certificate.
2. Then, in Foundry, you should use the certificated DNS --> instead of the plain IP address, you should type in the GoDice module config this address: **wss://godice-connector.com:8596**

Please see the instructions here (also find it through the module config support button):
https://drive.google.com/file/d/15Ksa4JAfPP_M0fW2-32sEUHTvPg5ybz1/view?usp=sharing

here is the RAR with the bat file:
https://drive.google.com/file/d/1rSbjqKtvn0a-fZ2Px2WgpOwBy4z57m_k/view?usp=sharing

Hope this helps!

**Comment by Simon-Stone** [comment]
Thanks! I am using a Mac, though. Are there equivalent instructions for Mac?

**Comment by AKparticula** [comment]
Unfortunately we can allow this only on windows as of now. sorry.
I am at least glad that you can use the other method.



   Amit Katz

*   Particula** ltd.* | *GoDice Product Manager*

   particula-tech.com

   Mobile/WhatsApp:+972508431849

    What is GoDice <https://www.youtube.com/watch?v=DIH0D06kLsw>
    Who are Particula <https://www.youtube.com/watch?v=8QqstAozG64>

**Comment by Simon-Stone** [comment]
Could you make just the pem file available? I might be able to add it as a trusted certificate on my own.

**Comment by ParticulaCode** [comment]
Hey, sure.
Please download it from here:
https://drive.google.com/file/d/1pveXDvGrwBQWhgS2F29tDut5XY-YpD8h/view?usp=sharing

Please let me know if it solved your issue

**Comment by Simon-Stone** [comment]
Thanks!

I managed to get SSL working on my Mac: 

I double-clicked the certificate to add it to the login keychain. I then right-clicked the certificate in the list and set it to Always Trust.
Then, I added my GoDice app IP  and host name `godice-connector.com` to the `/private/etc/hosts` file. 

Now everything is working just fine! Thanks for your help!

**Comment by ParticulaCode** [comment]
Amazing! Really happy to hear that! Have fun :)
